### ISSUE TITLE
Issue with [::-1] on a string

### ISSUE THREAD

**Issue by fbouchet** [nohtyprm/MrPython#104]
MrPython gets stuck when writing a program that involves the operation [::-1] on a string. Here is a minimal working example that triggers the issue:

```
def f():
    """->str"""
    # s: str
    s="test"
    return s[::-1]

assert f()=="test"
```
It seems a "Not Python-101" error should be raised but gets stuck somewhere

**Comment by fredokun** [comment]
This was in fact a bug in the parser for Slices, the fix is in commit https://github.com/nohtyprm/MrPython/commit/b821c07fefdc7590f33e2cbfb065b53658355ff8 
... It's not Non-Python101 by the way.
