### ISSUE TITLE
Interpreter output file permission (and related) issues

### ISSUE THREAD

**Issue by cbouilla** [nohtyprm/MrPython#105]
Many students try to install mrpython under Windows. A reoccurring bug is that evaluating expressions fails because of a permission problem. In `PyInterpreter`, line 106 tries to open for writing a file `interpreter_output` in the current directory. This fails (with a `PermissionDenied` Exception) when opening `Application.py` from the command line, regardless of what is the current directory.

**Comment by fredokun** [comment]
There are multiple issues with this file  (the same problem occurs with IDLE btw)... I'll try to use the "temp file" creation functions from the standard lib (hopefully they work also on windows).

**Comment by cbouilla** [comment]
This problem also happens in PPTI rooms when students run mrpython from a non-writable directory. There is no error message, instead mrpython hangs. It would be nice to catch the exception and report the problem to the users...

**Comment by fredokun** [comment]
ok, I'll try to address this issue ASAP

**Comment by cbouilla** [comment]
Le problème continue sous Windows. Un étudiant écrit :

> Je vous contact car j’ai téléchargé Mrpython sur mon pc pour refaire les exercices. Lorsque je rentre une fonction dans la zone 
> d’édition et que j’appuie sur exécuter il ne se passe plus rien. L’exécution ne finit pas et sur la fenêtre de terminal il y a écrit : 
> errno13 permission denied « interpreter output ». Que dois je faire pour régler ce problème ? 

Il a précisé ensuite : 

> Je suis sous Windows 10, j’ai téléchargé MrPython v4.0.1 via l’installateur pour Windows 10 en suivant les étapes 
> données sur le site, j’ai aussi téléchargé en parallèle Python étant un pré-requis si je me trompe pas.

**Comment by fredokun** [comment]
In commit dc3e23f78b1ea22e3140e39ccdf9b0c77a7ba454 I think there's a solution.
I'll make some tests before merging into master and making an updated installer.

**Comment by fredokun** [comment]
This has been merged and the problem seems now mitigated.
