### ISSUE TITLE
chained comparisons allowed?

### ISSUE THREAD

**Issue by fbouchet** [nohtyprm/MrPython#108]
MrPython currently raises no warning when using chained comparisons (e.g. a<b<c), which is obviously [fine in Python](https://docs.python.org/3/reference/expressions.html#comparisons), but I believe it goes against what is encouraged in Python101 (section 2.3.2 of the course and all examples in the exercises).

Unless I'm mistaken, it would be a logical enhancement for MrPython to encourage students to instead use the combination of boolean comparisons (e.g. a<b and b<c, in the previous case).

**Comment by fredokun** [comment]
We decided to support chained comparisons for "in-between" tests, especially for real number approximations using floats.

```python
assert 0.1 <= my-fun(4, 2) <= 0.3
```

But maybe a warning should be issued when used within functions...
