### ISSUE TITLE
"add" can not used as name of a function (but it used to)

### ISSUE THREAD

**Issue by bereziat** [nohtyprm/MrPython#146]
```python
def add(a: int) -> int:
   """ """
   return a+1
assert add( 1) == 2
```
stderr:
```
AttributeError: 'NoneType' object has no attribute 'alias'
```

**Comment by fredokun** [comment]
There is an ambiguity in the typechecker with the `.add` method, so the function name `add`  is now reserved in student mode,  but now there is an adequate error message.  This is implemented in commit c573e9255b542752b4c2f84de80865932c9c982f.
