### ISSUE TITLE
Copy then paste with cmd+v on MacOS pastes twice

### ISSUE THREAD

**Issue by programLyrique** [nohtyprm/MrPython#17]
With version 217d512c58b83c6874fd9b9d82f929cba9367daf on MacOSX Yosemite 10.10.5

How to reproduce:
- select some text
- copy: cmd+c
- paste: cmd+v

The copied string is pasted twice (as if it was concatenated to itself).

Ex: 
- blabla is copied
- when pasting with cmd+v, I get blablablabla

Copyng from MrPython and pasting in another application works as expected, so the buf seems to rather come from the paste operation with cmd+v.
When I use the "paste" operation from the menu bar, it pastes only blabla as expected.

**Comment by fredokun** [comment]
Probably solved... reopen if not...
