### ISSUE TITLE
extra string make the process hang up

### ISSUE THREAD

**Issue by cbouilla** [nohtyprm/MrPython#173]
Exemple de code problématique :

```python
"""Ceci va tout faire planter"""

def f(x : int) -> int:
    """
    une belle fonction
    """
    return x + 1
```

**Comment by cbouilla** [comment]
(si on retire la chaine de caractères au début, tout va bien). Ceci perturbe pas mal les étudiants.

**Comment by fredokun** [comment]
Attention, les commentaires Python ne s'écrivent pas avec des chaînes:

```python
# Ceci ne fait rien planter
```

Cependant, je vais faire un message plus "sympathique", merci pour le retour

**Comment by fredokun** [comment]
MrPython does not hang anymore, cf. https://github.com/nohtyprm/MrPython/commit/a027560e9754c1edceabc8258ede64e8a8383bc6
But string as comments are **not** allowed, it's not a good practice
