### ISSUE TITLE
pas de reconnaissance de math.log

### ISSUE THREAD

**Issue by lioneltabourier** [nohtyprm/MrPython#176]
MrPython 4.0.1 does not recognize math.log in student mode

```import math
def my_log (x: float) -> float :
    """ precondition: x > 0 """
    return math.log(x)
```

```==> Problème d'appel: je ne connais pas de fonction dont le nom est 'math.log'```

**Comment by fredokun** [comment]
Added in https://github.com/nohtyprm/MrPython/commit/a0587a2bd123068d9389ebf545b6ea8b6da97aff
