### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by LeGmask** [nohtyprm/MrPython#178]
![image](https://user-images.githubusercontent.com/53308142/146421372-aca1bdc1-947b-4fc4-b073-95cc6b854481.png)

**Comment by yannilefki** [comment]
I'm having the exact same problem with my installation.
![Capture d’écran du 2022-09-08 18-44-58](https://user-images.githubusercontent.com/80094663/189179292-2b79ffe8-bfdf-4b9c-8637-c2a3585f0288.png)

I'm trying to install mrpython on ubuntu 22.04 but my terminal is answering this after i write "python3 ./Application.py"

**Comment by LeGmask** [comment]
> I'm having the exact same problem with my installation. ![Capture d’écran du 2022-09-08 18-44-58](https://user-images.githubusercontent.com/80094663/189179292-2b79ffe8-bfdf-4b9c-8637-c2a3585f0288.png)
> 
> I'm trying to install mrpython on ubuntu 22.04 but my terminal is answering this after i write "python3 ./Application.py"

use my fork see #179

**Comment by yannilefki** [comment]
Thank you it works like a charm

**Comment by fredokun** [comment]
closed by 82c0421b726220ade7574cf208cc2918783576f7
