### ISSUE TITLE
Interface changement de mode

### ISSUE THREAD

**Issue by fgallaire** [nohtyprm/MrPython#181]
Le bouton de changement de mode expert <-> étudiant, que l'on utilise
pour ainsi dire jamais, est positionné entre les autres boutons qui
sont eux utilisés de manière intensive, amenant régulièrement à un
clic inapproprié.

L'exil de ce bouton à l'extrême droite de l'interface,
ou une boîte de dialogue de confirmation,
sont des solutions possibles à ce problème.

**Comment by fredokun** [comment]
A confirmation is now asked the first time you selection the  change mode button, cf. commit https://github.com/nohtyprm/MrPython/commit/37e87cf86ce02457b9a36a140b3caf319f2eed66
