### ISSUE TITLE
Version 4.x is incompatible with python >= 3.10

### ISSUE THREAD

**Issue by Nagisa19** [nohtyprm/MrPython#186]
In PyParse.py if using python >= 3.10, ```from collections import Mapping``` should be ```from collections.abc import Mapping```

**Comment by Nagisa19** [comment]
This can be changed to :
import re
import sys
try:
    from collections import Mapping
except ImportError:
    from collections.abc import Mapping

from functools import partial

**Comment by fredokun** [comment]
duplicate with #178,  switch to v.5.x.y
