### ISSUE TITLE
The typechecking of empty `return` statements stalls

### ISSUE THREAD

**Issue by Kerl13** [nohtyprm/MrPython#63]
The type-checking of this function stalls

```python
def f(x):
    """ int -> NoneType """
    return
```

Whereas this works:

```python
def f(x):
    """ int -> NoneType """
    return None
```

(MrPython @ e8a212a44357ac6c47ce25e02f30e019ff4d3bfe)

**Comment by fredokun** [comment]
fixed in https://github.com/nohtyprm/MrPython/commit/cd13e26f7054fc14c1418d6d409492106420f9b9

(return without expression is not supported by the Python101 sublanguage)
