### ISSUE TITLE
Type-checker fails on bad code, resulting in MrPython being stuck

### ISSUE THREAD

**Issue by rmonat** [nohtyprm/MrPython#69]
When executing this piece of code in Python (which is not valid, since i should be `in range(len(s))`):

```python
def f(s):
    """str -> int"""
    # i : int
    for i in len(s):
        pass
```
The typechecking fails and MrPython remains stuck. I think this should be changed to let the user know there is an error with his/her code.

**Comment by fredokun** [comment]
fixed in commit https://github.com/nohtyprm/MrPython/commit/fcb0e4721b5c4c3903e6a56d44017469b2a74759
