### ISSUE TITLE
personnal type seems not to work

### ISSUE THREAD

**Issue by Cyrcocq** [nohtyprm/MrPython#78]
Hi,

I hope I'm not wrong:

"# type BIBLIOTHEQUE = dict[str: set[str]]"

as code and it doesn't compile.

Is'nt it a bug?

regards.

Cyril

**Comment by wegank** [comment]
Unable to reproduce this error on MrPython v.2.0.0-rc3. Have you updated MrPython to the latest version?

**Comment by Cyrcocq** [comment]
Bonjour,
J'utilise la version
v.2.0.0-beta-4 -- mode étudiant
Sur un python 3.7.1

Ne trouvant pas la version ici, j'ai tenté la mise à jour...
Je suis passé en 2.0.0 RC2...
Et ça marche.

Merci.
