### ISSUE TITLE
list[Number] with int and float works as command but not as assert

### ISSUE THREAD

**Issue by Cyrcocq** [nohtyprm/MrPython#79]
Bonjour,

Avec un code de ce type:

def donne_couples(L1,L2):
    """list[Number] * list[Number] -> list[tuple[Number,Number]]"""
(...)
    return Res

assert donne_couples([42],[4, 7.2])==[(42, 4), (42, 7.2)]

ne fonctionne pas, avec un message: 
Eléments hétérogènes (restriction Python 101): Tous les élements doivent être du même type 'int' mais cet élément est d'un type incompatible: float
alors que 
donne_couples([42],[4, 7.2])
me renvoie
[(42, 4), (42, 7.2)]

Merci.

Cyril COCQUEREL

**Comment by wegank** [comment]
Pourriez-vous fournir la réalisation (code) de donne_couples et ses spécifications ? Merci.

**Comment by Cyrcocq** [comment]
Bonjour,
Comme mon autre intervention ici, elle devait être liée à une ancienne version de Mr Python.
Cela fonctionne également désormais.

Merci.
Et désolé pour le dérangement :-)

Et sinon, mon code est:

def donne_couples(L1,L2):
    """list[Number] * list[Number] -> list[tuple[Number,Number]]
    Hypothèse : tous les élements L[i] de L sont tels que L[i]<=len(s)"""

    #Res : list[tuple[Number,Number]]
    Res=[]

    #n : int
    n=0

    #i : int
    i=0

    #j : int
    j=0

    while(i<len(L1)):
        while(j<len(L2)):
            if L2[j]<L1[i]:
                Res.append((L1[i],L2[j]))
                n = n+1
                if n == 3 :
                    n = 0
                    j = len(L2)      
            j=j+1
        i=i+1
        j=0

    return Res

assert donne_couples([42],[4, 7, 2, 11, 38, 75])==[(42, 4), (42, 7), (42, 2)]
assert donne_couples([1],[4.0, 7.0, 2.8, 11.0, 38.0, 75.99])==[]           
assert donne_couples([42.0, 4, 9],[38.0, 2, 7, 4, 9]) == [(42, 38), (42, 2), (42, 7), (4, 2), (9, 2), (9, 7)]

Ce code plantait au niveau du 3e assert (dans lequel je viens de rajouter les ".0 des 1eres valeurs qui précédemment plantaient...

(à l'invite, l'évaluation de 
donne_couples([42.0, 4, 9],[38.0, 2, 7, 4, 9])  
renvoie
[(42.0, 38.0), (42.0, 2), (42.0, 7), (4, 2), (9, 2), (9, 7)]
.

Du coup au passage j'ai découvert l'égalité entre 0 et 0.0.


Merci.

Cordialement.

Cyril C.
